#!/bin/bash

nicA="${nicA:?Missing "nicA" parameter, this should be set to the first physical ethernet adapter (e.g. nicA=eth1)}"
nicB="${nicB:?Missing "nicB" parameter, this should be set to the first physical ethernet adapter (e.g. nicB=eth2)}"

nicB_ip4="${nicB_ip4:-198.18.10.10/24}"

bridgeA="${bridgeA:-bridgeA}"
bridgeA_ip4="${bridgeA_ip4:-198.18.10.10/24}"

vlanA_id="${vlanA_id:-10}"
vlanA_ip4="${vlanA_ip4:-198.18.11.10/24}"
vlanA="${vlanA:-$nicA.$vlanA_id}"

test_description()
{
	cat - <<-EOT

	Test "wicked ifcheck --changed"

	- check behavior on ethernet($nicA,$nicB), bridge($bridgeA) and VLAN($vlanA) device
	- check with and without autogenerated port/lower configs
	- check changed, deleted and new config

	EOT
}

rc_codes=(
	0  NI_WICKED_RC_SUCCESS
	1  NI_WICKED_RC_ERROR
	2  NI_WICKED_RC_USAGE
	3  NI_WICKED_RC_NOT_IMPLEMENTED
	4  NI_WICKED_RC_NOT_ALLOWED
	6  NI_WICKED_RC_NOT_CONFIGURED
	7  NI_WICKED_RC_NOT_RUNNING
	7  NI_WICKED_RC_NO_DEVICE
	12 NI_WICKED_RC_IN_PROGRESS
)

st_codes=(
	0   NI_WICKED_ST_OK
	1   NI_WICKED_ST_ERROR
	2   NI_WICKED_ST_FAILED
	3   NI_WICKED_ST_UNUSED
	4   NI_WICKED_ST_USAGE

	155 NI_WICKED_ST_DISABLED
	156 NI_WICKED_ST_UNCONFIGURED
	157 NI_WICKED_ST_NO_DEVICE
	158 NI_WICKED_ST_NOT_RUNNING
	159 NI_WICKED_ST_NO_CONFIG
	162 NI_WICKED_ST_IN_PROGRESS
	163 NI_WICKED_ST_CHANGED_CONFIG
	164 NI_WICKED_ST_ENSLAVED
	165 NI_WICKED_ST_NOT_IN_STATE
	166 NI_WICKED_ST_PERSISTENT_ON
	167 NI_WICKED_ST_USERCONTROL_ON
	168 NI_WICKED_ST_NO_CARRIER
)

exit_code_to_str()
{
	length=${#rc_codes[@]}
	for (( j=0; j<length; j+=2 ));
	do
		code=${rc_codes[$j]}
		name=${rc_codes[$(($j + 1))]}
		if [[ "$code" -eq "$1" ]]; then
			echo -n "$name($code)";
			return 0
		fi
	done

	length=${#st_codes[@]}
	for (( j=0; j<length; j+=2 ));
	do
		code=${st_codes[$j]}
		name=${st_codes[$(($j + 1))]}
		if [[ "$code" -eq "$1" ]]; then
			echo -n "$name($code)";
			return 0
		fi
	done
	fatal "Unknown exit code $1"
}

exit_code()
{
	length=${#st_codes[@]}
	for (( j=0; j<length; j+=2 ));
	do
		code=${st_codes[$j]}
		name=${st_codes[$(($j + 1))]}
		if [[ "$name" == "$1" ]] || [[ ${name:13} == "$1" ]]; then
			echo -n "$code";
			return 0
		fi
	done

	length=${#rc_codes[@]}
	for (( j=0; j<length; j+=2 ));
	do
		code=${rc_codes[$j]}
		name=${rc_codes[$(($j + 1))]}
		if [[ "$name" == "$1" ]] || [[ ${name:13} == "$1" ]]; then
			echo -n "$code";
			return 0
		fi
	done
	fatal "Unknown exit code name $1"
}

show_cfg()
{
	{
		echo "== $1 =="
		cat "$1"
		echo ""
	} | tee "config-step-${step}.xml"
}

check()
{
	cmd=$1
	shift
	exp_ret=0
	while [[ $# -gt 0 ]]; do
		ifc=$1; shift
		if [[ $ifc == "--expect" ]]; then
			exp_ret=$1; shift
			[[ "$exp_ret" =~ ^[0-9]+$ ]] || exp_ret=$(exit_code "$exp_ret")
			continue
		fi
		echo "== cmd: $cmd $ifc =="
		$cmd "$ifc"
		local e=$?
		[[ $e -eq $exp_ret ]] || fatal "'$cmd $ifc' failed (expect:$(exit_code_to_str $exp_ret) got:$(exit_code_to_str $e)"

		echo "--> $(exit_code_to_str $e)"
		echo ""
	done
}

check_ifstatus()
{
	check "wicked $wdebug ifstatus " --expect "OK" "$@"
}

check_ifstatus_no_device()
{
	check_ifstatus --expect NO_DEVICE "$@"
}

check_ifstatus_unconfigured()
{
	check_ifstatus --expect UNCONFIGURED "$@"
}

check_ifcheck_changed()
{
	check "wicked $wdebug ifcheck --changed" --expect "CHANGED_CONFIG" "$@"
}

check_ifcheck_not_changed()
{
	check_ifcheck_changed --expect OK "$@"
}

fatal()
{
	echo "FATAL ERROR: $1"
	exit 3
}

step0()
{
	bold "=== $step -- Cleanup configuration"

	for i in "$nicB" "$nicA" "$bridgeA" "$vlanA"; do
		rm -f "$dir/ifcfg-$i"
	done
	wicked $wdebug ifreload all

	check_ifstatus_unconfigured "$nicB" "$nicA"
	check_ifstatus_no_device "$bridgeA" "$vlanA"

	sed -E '1d;2d;/^([^#])/d;/^$/d' $BASH_SOURCE | tee "config-step-${step}.cfg"
	wicked show-config | tee "config-step-${step}.xml"
}


step1()
{
	bold "=== $step -- Ethernet device"

	check_ifcheck_not_changed "$nicB"
	cat > "$dir/ifcfg-$nicB" <<-EOT
		STARTMODE=auto
		BOOTPROTO=static
		IPADDR=$nicB_ip4
		ZONE=public
	EOT
	show_cfg "$dir/ifcfg-$nicB"
	check_ifcheck_changed "$nicB"
	check "wicked $wdebug ifup" "$nicB"
	check_ifcheck_not_changed "$nicB"

	bold "-> Change configuration $dir/ifcfg-$nicB"
	sed -i '/IPADDR=/cIPADDR=192.16.0.2/24' "$dir/ifcfg-$nicB"
	check_ifcheck_changed "$nicB"
	check "wicked $wdebug ifup" "$nicB"
	check_ifcheck_not_changed "$nicB"

	bold "-> ifdown $nicB"
	check "wicked $wdebug ifdown" "$nicB"
	check_ifcheck_changed "$nicB"
	check_ifstatus_unconfigured "$nicB"

	bold "-> ifup $nicB"
	check "wicked $wdebug ifup" "$nicB"
	check_ifcheck_not_changed "$nicB"
	check_ifstatus "$nicB"

	bold "-> Delete config $dir/ifcfg-$nicB"
	rm "$dir/ifcfg-$nicB"
	check_ifcheck_changed "$nicB"

	bold "-> ifdown $nicB"
	check "wicked ifdown" "$nicB"
	check_ifcheck_not_changed "$nicB"
	check_ifstatus_unconfigured "$nicB"
}

step2()
{
	bold "=== $step -- Bridge with autogenerated port config"
	check_ifstatus_no_device "$bridgeA"
	cat > "$dir/ifcfg-$bridgeA" <<-EOT
		STARTMODE=auto
		BOOTPROTO=static
		BRIDGE=yes
		BRIDGE_STP=off
		BRIDGE_PORTS=$nicA
		IPADDR=$bridgeA_ip4
		ZONE=public
	EOT
	show_cfg "$dir/ifcfg-$bridgeA"
	check_ifcheck_changed "$bridgeA"
	check_ifcheck_changed "$nicA"
	check_ifcheck_not_changed "$nicB"
	check "wicked $wdebug ifup" "$bridgeA"
	check_ifcheck_not_changed "$bridgeA"
	check_ifcheck_not_changed "$nicA"
	echo "-> Change configuration $dir/ifcfg-$bridgeA"
	sed -i '/IPADDR=/cIPADDR=192.16.0.2/24' "$dir/ifcfg-$bridgeA"
	check_ifcheck_changed "$bridgeA"
	check_ifcheck_not_changed "$nicA"
	check "wicked $wdebug ifup" "$bridgeA"
	check_ifcheck_not_changed "$bridgeA"
	check_ifcheck_not_changed "$nicA"
	echo "-> Delete config $dir/ifcfg-$bridgeA"
	rm "$dir/ifcfg-$bridgeA"
	check_ifcheck_changed "$bridgeA"
	check_ifcheck_changed "$nicA"
	check "wicked $wdebug ifdown" "$bridgeA"
	check_ifstatus_no_device "$bridgeA"
	check_ifcheck_changed --expect NI_WICKED_RC_NO_DEVICE "$bridgeA"
	check_ifstatus_unconfigured "$nicA"
	check_ifcheck_not_changed "$nicA"
}

step3()
{
	bold "=== $step -- Bridge with explicit port config"

	check_ifstatus_no_device "$bridgeA"
	cat > "$dir/ifcfg-$bridgeA" <<-EOT
		STARTMODE=auto
		BOOTPROTO=static
		BRIDGE=yes
		BRIDGE_STP=off
		BRIDGE_PORTS=$nicA
		IPADDR=192.18.0.1/24
		ZONE=public
	EOT
	show_cfg "$dir/ifcfg-$bridgeA"
	cat > "$dir/ifcfg-$nicA" <<-EOT
		STARTMODE=auto
		BOOTPROTO=none
	EOT
	show_cfg "$dir/ifcfg-$nicA"
	check "wicked $wdebug ifup" "$nicA" # trigger ifup on $bridgeA
	check_ifcheck_not_changed "$bridgeA"
	check_ifcheck_not_changed "$nicA"
	check "wicked $wdebug ifup" "$bridgeA"
	check_ifcheck_not_changed "$bridgeA"
	check_ifcheck_not_changed "$nicA"
	echo "-> Change configuration $dir/ifcfg-$bridgeA"
	sed -i '/IPADDR=/cIPADDR=192.16.0.2/24' "$dir/ifcfg-$bridgeA"
	check_ifcheck_changed "$bridgeA"
	check_ifcheck_not_changed "$nicA"
	check "wicked $wdebug ifup" "$bridgeA"
	check_ifcheck_not_changed "$bridgeA"
	check_ifcheck_not_changed "$nicA"
	echo "-> Delete config $dir/ifcfg-$bridgeA"
	rm "$dir/ifcfg-$bridgeA"
	check_ifcheck_changed "$bridgeA"
	check_ifcheck_changed "$nicA"
	check "wicked $wdebug ifdown" "$bridgeA"
	check_ifstatus_no_device "$bridgeA"
	check_ifcheck_changed "$nicA"
	echo "-> Delete config $dir/ifcfg-$nicA"
	rm "$dir/ifcfg-$nicA"
	check_ifstatus_no_device "$bridgeA"
	check_ifcheck_changed --expect NI_WICKED_RC_NO_DEVICE "$bridgeA"
	check_ifstatus_unconfigured "$nicA"
	check_ifcheck_not_changed "$nicA"
}

step4()
{
	bold "=== $step -- Bridge no PORTS => no-carrier"
	check_ifstatus_no_device "$bridgeA"
	cat > "$dir/ifcfg-$bridgeA" <<-EOT
		STARTMODE=auto
		BOOTPROTO=static
		BRIDGE=yes
		BRIDGE_STP=off
		IPADDR=192.18.0.1/24
		ZONE=public
	EOT
	show_cfg "$dir/ifcfg-$bridgeA"
	check_ifcheck_changed "$bridgeA"
	check "wicked $wdebug ifup" --expect NI_WICKED_ST_NO_CARRIER "$bridgeA"
	check_ifcheck_not_changed "$bridgeA"
	echo "-> Change configuration $dir/ifcfg-$bridgeA"
	sed -i '/IPADDR=/cIPADDR=192.16.0.2/24' "$dir/ifcfg-$bridgeA"
	check_ifcheck_changed "$bridgeA"
	check "wicked $wdebug ifup" --expect NI_WICKED_ST_NO_CARRIER "$bridgeA"
	check_ifcheck_not_changed "$bridgeA"
	echo "-> Delete config"
	rm "$dir/ifcfg-$bridgeA"
	check_ifcheck_changed "$bridgeA"
	check "wicked $wdebug ifdown" "$bridgeA"
	check_ifstatus_no_device "$bridgeA"
	check_ifcheck_changed --expect NI_WICKED_RC_NO_DEVICE "$bridgeA"
}

step5()
{
	bold "=== $step -- VLAN $vlanA with autogenerated link device config"
	check_ifstatus_no_device "$vlanA"
	check_ifstatus_unconfigured "$nicA"
	cat > "$dir/ifcfg-$vlanA" <<-EOT
		STARTMODE=auto
		BOOTPROTO=static
		ETHERDEVICE=$nicA
		IPADDR=192.18.0.1/24
		ZONE=public
	EOT
	show_cfg "$dir/ifcfg-$vlanA"
	check_ifcheck_changed "$vlanA"
	check_ifcheck_changed "$nicA"
	check "wicked $wdebug ifup" "$vlanA"
	check_ifcheck_not_changed "$vlanA"
	check_ifcheck_not_changed "$nicA"
	echo "-> Change configuration $dir/ifcfg-$vlanA"
	sed -i '/IPADDR=/cIPADDR=192.16.0.2/24' "$dir/ifcfg-$vlanA"
	check_ifcheck_changed "$vlanA"
	check_ifcheck_not_changed "$nicA"
	check "wicked $wdebug ifup" "$vlanA"
	check_ifcheck_not_changed "$vlanA"
	check_ifcheck_not_changed "$nicA"
	echo "-> Delete config $dir/ifcfg-$vlanA"
	rm "$dir/ifcfg-$vlanA"
	check_ifcheck_changed "$vlanA"
	check_ifcheck_changed "$nicA"
	check "wicked $wdebug ifdown" "$vlanA"
	check_ifstatus_no_device "$vlanA"
	echo "!!! WARNING: is this behavior expected?!? The port $nicA has a autogenerated configbut it isn't cleaned up when ifdown the upper interface!"
	check_ifcheck_changed "$nicA"
	check "wicked $wdebug ifdown" "$nicA"  # cleanup because of unexpected behavior above!
}

step6()
{
	bold "=== $step -- VLAN $vlanA with explicit lower device config"

	check_ifstatus_no_device "$vlanA"
	check_ifstatus_unconfigured "$nicA"
	cat > "$dir/ifcfg-$vlanA" <<-EOT
		STARTMODE=auto
		BOOTPROTO=static
		ETHERDEVICE=$nicA
		IPADDR=192.18.0.1/24
		ZONE=public
	EOT
	show_cfg "$dir/ifcfg-$vlanA"
	cat > "$dir/ifcfg-$nicA" <<-EOT
		STARTMODE=auto
		BOOTPROTO=none
	EOT
	show_cfg "$dir/ifcfg-$nicA"
	check_ifcheck_changed "$vlanA"
	check_ifcheck_changed "$nicA"
	check "wicked $wdebug ifup" "$nicA"
	check_ifcheck_changed "$vlanA"
	check_ifcheck_not_changed "$nicA"
	check "wicked $wdebug ifup" "$vlanA"
	check_ifcheck_not_changed "$vlanA"
	check_ifcheck_not_changed "$nicA"
	echo "-> Change configuration $dir/ifcfg-$vlanA"
	sed -i '/IPADDR=/cIPADDR=192.16.0.2/24' "$dir/ifcfg-$vlanA"
	check_ifcheck_changed "$vlanA"
	check_ifcheck_not_changed "$nicA"
	check "wicked $wdebug ifup" "$vlanA"
	check_ifcheck_not_changed "$vlanA"
	check_ifcheck_not_changed "$nicA"
	echo "-> Delete config $dir/ifcfg-$vlanA"
	rm "$dir/ifcfg-$vlanA"
	check_ifcheck_changed "$vlanA"
	check_ifcheck_not_changed "$nicA"
	check "wicked $wdebug ifdown" "$vlanA"
	check_ifstatus_no_device "$vlanA"
	check_ifcheck_not_changed "$nicA"
}

step99()
{
	step0
}


. ../../lib/common.sh
